### ISSUE TITLE
Create Main Activity

### ISSUE THREAD

**Issue by bpglaser** [toastymmm/mobile#1]
The main activity will need to display the map, floating action button, sidebar, and links to the other activities.

**Comment by SecondThread** [comment]
Logout should be included in the floating action button

**Comment by bpglaser** [comment]
Logout in the floating action button? I was reserving the FAB functionality for the message creation. I was going to move logout to the sidebar.

**Comment by bpglaser** [comment]
Main activity is mostly done. I just need to hook up the edit button to the edit activity after I create it.
